const cfg=window.APP_CONFIG||{}; const ok=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR_PROJECT')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('YOUR_');
const sb=ok?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const loginView=document.getElementById('loginView'),adminView=document.getElementById('adminView'),ordersBody=document.getElementById('ordersBody'),driversBody=document.getElementById('driversBody');
let orders=[],drivers=[];
const statusMap={new:'جديد',contacted:'تم التواصل',confirmed:'تم تأكيد السيارة',on_the_way:'السائق في الطريق',completed:'مكتمل',cancelled:'ملغي'};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));} function waPhone(p){let x=String(p).replace(/\D/g,''); if(x.startsWith('0'))x='971'+x.slice(1); if(!x.startsWith('971'))x='971'+x; return x;}
function when(o){return o.request_type==='now'?'الآن':new Date(o.scheduled_at).toLocaleString('ar-AE',{dateStyle:'short',timeStyle:'short'});} function tel(p){return String(p).replace(/[^+\d]/g,'');}
async function boot(){if(!sb){document.getElementById('loginError').textContent='أضف بيانات Supabase في config.js أولًا.';document.getElementById('loginError').classList.remove('hidden');return;} const {data}=await sb.auth.getSession(); if(data.session) showAdmin();}
async function showAdmin(){loginView.classList.add('hidden');adminView.classList.remove('hidden');await loadAll();}
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault(); const box=document.getElementById('loginError');box.classList.add('hidden'); if(!sb){box.textContent='Supabase غير مهيأ.';box.classList.remove('hidden');return;} const {error}=await sb.auth.signInWithPassword({email:document.getElementById('email').value,password:document.getElementById('password').value}); if(error){box.textContent='بيانات الدخول غير صحيحة.';box.classList.remove('hidden');return;} showAdmin();};
document.getElementById('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload();};document.getElementById('refreshBtn').onclick=loadAll;
async function loadAll(){const [{data:o,error:oe},{data:d,error:de}]=await Promise.all([sb.from('ride_requests').select('*').order('created_at',{ascending:false}),sb.from('drivers').select('*').order('created_at',{ascending:false})]);if(oe||de){alert((oe||de).message);return;}orders=o||[];drivers=d||[];renderDrivers();renderOrders();}
function driverOptions(selected){return `<option value="">بدون سائق</option>`+drivers.filter(d=>d.is_available||d.id===selected).map(d=>`<option value="${d.id}" ${d.id===selected?'selected':''}>${esc(d.name)} — ${esc(d.car_number)}</option>`).join('');}
function renderOrders(){const q=document.getElementById('searchInput').value.trim().toLowerCase(),st=document.getElementById('statusFilter').value;const list=orders.filter(o=>(!st||o.status===st)&&(!q||o.order_number.toLowerCase().includes(q)||o.phone.toLowerCase().includes(q)));document.getElementById('countStat').textContent=`${list.length} طلب`;ordersBody.innerHTML=list.length?list.map(o=>{const d=drivers.find(x=>x.id===o.driver_id);const msg=encodeURIComponent(`طلب سيارة ${o.order_number}\nالعميل: ${o.customer_name}\nالهاتف: ${o.phone}\nالانطلاق: ${o.pickup}\nالوجهة: ${o.destination}\nالوقت: ${when(o)}\nالركاب: ${o.passengers}\nملاحظات: ${o.notes||'-'}`);return `<tr><td><strong>${esc(o.order_number)}</strong></td><td>${esc(o.customer_name)}</td><td>${esc(o.phone)}</td><td>${esc(o.pickup)}</td><td>${esc(o.destination)}</td><td>${esc(when(o))}</td><td>${o.passengers}</td><td>${esc(o.notes||'—')}</td><td><select class="status-select" onchange="updateStatus('${o.id}',this.value)">${Object.entries(statusMap).map(([k,v])=>`<option value="${k}" ${o.status===k?'selected':''}>${v}</option>`).join('')}</select></td><td><select class="driver-select" onchange="assignDriver('${o.id}',this.value)">${driverOptions(o.driver_id)}</select>${d?`<div class="muted" style="margin-top:5px">${esc(d.phone)} · ${esc(d.car_number)}</div>`:''}</td><td><div class="actions"><a class="mini" href="tel:${tel(o.phone)}">اتصال</a><a class="mini whatsapp" target="_blank" href="https://wa.me/${waPhone(o.phone)}?text=${encodeURIComponent('مرحبًا، بخصوص طلب السيارة رقم '+o.order_number)}">واتساب العميل</a>${d?`<a class="mini whatsapp" target="_blank" href="https://wa.me/${waPhone(d.phone)}?text=${msg}">إرسال للسائق</a>`:''}<button class="mini danger" onclick="deleteOrder('${o.id}')">حذف</button></div></td></tr>`}).join(''):`<tr><td colspan="11" class="muted">لا توجد طلبات مطابقة.</td></tr>`;}
function renderDrivers(){driversBody.innerHTML=drivers.length?drivers.map(d=>`<tr><td>${esc(d.name)}</td><td>${esc(d.phone)}</td><td>${esc(d.car_number)}</td><td>${esc(d.car_type)}</td><td><select class="status-select" onchange="toggleDriver('${d.id}',this.value)"><option value="true" ${d.is_available?'selected':''}>متاح</option><option value="false" ${!d.is_available?'selected':''}>غير متاح</option></select></td><td><button class="mini danger" onclick="deleteDriver('${d.id}')">حذف</button></td></tr>`).join(''):`<tr><td colspan="6" class="muted">لا يوجد سائقون بعد.</td></tr>`;}
document.getElementById('searchInput').oninput=renderOrders;document.getElementById('statusFilter').onchange=renderOrders;
window.updateStatus=async(id,status)=>{const {error}=await sb.from('ride_requests').update({status}).eq('id',id);if(error)alert(error.message);else{orders.find(o=>o.id===id).status=status;}};
window.assignDriver=async(id,driver_id)=>{const val=driver_id||null;const {error}=await sb.from('ride_requests').update({driver_id:val}).eq('id',id);if(error)alert(error.message);else{orders.find(o=>o.id===id).driver_id=val;renderOrders();}};
window.deleteOrder=async id=>{if(!confirm('حذف الطلب نهائيًا؟'))return;const {error}=await sb.from('ride_requests').delete().eq('id',id);if(error)alert(error.message);else{orders=orders.filter(o=>o.id!==id);renderOrders();}};
window.toggleDriver=async(id,v)=>{const is_available=v==='true';const {error}=await sb.from('drivers').update({is_available}).eq('id',id);if(error)alert(error.message);else drivers.find(d=>d.id===id).is_available=is_available;};
window.deleteDriver=async id=>{if(!confirm('حذف السائق؟'))return;const {error}=await sb.from('drivers').delete().eq('id',id);if(error)alert('لا يمكن حذف سائق مرتبط بطلب أو حدث خطأ: '+error.message);else{drivers=drivers.filter(d=>d.id!==id);renderDrivers();renderOrders();}};
document.getElementById('driverForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const payload={name:fd.get('name').trim(),phone:fd.get('phone').trim(),car_number:fd.get('car_number').trim(),car_type:fd.get('car_type').trim(),is_available:fd.get('is_available')==='true'};const {data,error}=await sb.from('drivers').insert(payload).select().single();if(error)alert(error.message);else{drivers.unshift(data);e.currentTarget.reset();renderDrivers();renderOrders();}};
boot();
