const cfg=window.APP_CONFIG||{};
const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
let rides=[],drivers=[],vehicles=[],driverFilter='pending';
const statusText={new:'جديد',searching:'جاري البحث',accepted:'تم القبول',on_the_way:'السائق في الطريق',arrived:'وصل السائق',started:'الرحلة جارية',completed:'مكتمل',cancelled:'ملغي',contacted:'تم التواصل',confirmed:'تم التأكيد'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dateTime(v){return v?new Date(v).toLocaleString('ar-AE',{dateStyle:'short',timeStyle:'short'}):'—'}
function badgeStatus(s){const cls=['approved','active','completed'].includes(s)?'ok':['pending','trial','new','searching'].includes(s)?'warn':['rejected','suspended','cancelled','expired'].includes(s)?'bad':'info';return `<span class="status ${cls}">${esc(statusText[s]||({approved:'معتمد',pending:'قيد المراجعة',rejected:'مرفوض',suspended:'موقوف',trial:'تجريبي',active:'نشط',expired:'منتهي'})[s]||s)}</span>`}
async function assertAdmin(){const {data:u}=await sb.auth.getUser();if(!u.user)return false;const {data:p}=await sb.from('profiles').select('role').eq('user_id',u.user.id).maybeSingle();return p?.role==='admin'}
async function boot(){const {data}=await sb.auth.getSession();if(data.session&&await assertAdmin())showAdmin()}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').classList.add('hidden');const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginError').textContent='بيانات الدخول غير صحيحة.';$('loginError').classList.remove('hidden');return}if(!(await assertAdmin())){await sb.auth.signOut();$('loginError').textContent='هذا الحساب ليس مديرًا.';$('loginError').classList.remove('hidden');return}showAdmin()};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refreshBtn').onclick=loadAll;
async function showAdmin(){$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');await loadAll()}
async function loadAll(){const [r,d,v]=await Promise.all([sb.from('ride_requests').select('*').order('created_at',{ascending:false}),sb.from('drivers').select('*').order('created_at',{ascending:false}),sb.from('vehicles').select('*').order('created_at',{ascending:false})]);if(r.error||d.error||v.error){alert((r.error||d.error||v.error).message);return}rides=r.data||[];drivers=d.data||[];vehicles=v.data||[];renderAll();$('lastUpdated').textContent='آخر تحديث '+new Date().toLocaleTimeString('ar-AE',{hour:'2-digit',minute:'2-digit'})}
function renderAll(){renderOverview();renderRides();renderDrivers();renderSubscriptions()}
function renderOverview(){const today=new Date();today.setHours(0,0,0,0);$('kpiToday').textContent=rides.filter(r=>new Date(r.created_at)>=today).length;$('kpiWaiting').textContent=rides.filter(r=>!r.driver_id&&['new','searching'].includes(r.status)).length;$('kpiAvailable').textContent=drivers.filter(d=>d.approval_status==='approved'&&d.is_available&&!d.is_busy).length;$('kpiPending').textContent=drivers.filter(d=>d.approval_status==='pending').length;const issues=[];drivers.filter(d=>d.approval_status==='pending').slice(0,4).forEach(d=>issues.push(`<button class="attention" onclick="openView('drivers')"><span>سائق جديد ينتظر الاعتماد</span><strong>${esc(d.name)}</strong></button>`));rides.filter(r=>r.dispatch_state==='no_driver'||(!r.driver_id&&r.status==='searching'&&Date.now()-new Date(r.created_at)>120000)).slice(0,4).forEach(r=>issues.push(`<button class="attention" onclick="openView('rides')"><span>طلب لم يجد سائقًا</span><strong>${esc(r.order_number)} · ${esc(r.pickup)}</strong></button>`));$('attentionList').innerHTML=issues.length?issues.join(''):'<div class="empty">لا توجد حالات تحتاج تدخلك الآن ✓</div>'}
function driverFor(id){return drivers.find(d=>d.id===id)}function vehicleFor(driverId){return vehicles.find(v=>v.driver_id===driverId)}
function renderRides(){const q=$('searchInput').value.trim().toLowerCase(),st=$('statusFilter').value;const list=rides.filter(r=>(!st||r.status===st)&&(!q||r.order_number.toLowerCase().includes(q)||r.phone.toLowerCase().includes(q)));$('ridesCount').textContent=list.length+' طلب';$('ridesCards').innerHTML=list.length?list.map(r=>{const d=driverFor(r.driver_id);return `<article class="entity-card ride"><div class="entity-top"><div><strong class="entity-title">${esc(r.order_number)}</strong><span class="entity-sub">${dateTime(r.created_at)}</span></div>${badgeStatus(r.status)}</div><div class="route"><div><small>الانطلاق</small><b>${esc(r.pickup)}</b><span>${esc(r.pickup_zone||'')}</span></div><i>←</i><div><small>الوجهة</small><b>${esc(r.destination)}</b></div></div><div class="facts"><div><small>العميل</small><b>${esc(r.customer_name)}</b></div><div><small>الهاتف</small><b dir="ltr">${esc(r.phone)}</b></div><div><small>السائق</small><b>${d?esc(d.name):'جاري البحث تلقائيًا'}</b></div><div><small>الركاب</small><b>${r.passengers}</b></div></div><div class="card-actions"><a class="btn btn-dark" href="tel:${esc(r.phone)}">اتصال بالعميل</a>${!r.driver_id&&['new','searching'].includes(r.status)?'<span class="auto-note">⚡ التعيين تلقائي</span>':''}${r.status!=='completed'&&r.status!=='cancelled'?`<button class="btn btn-outline-danger" onclick="cancelRide('${r.id}')">إلغاء الطلب</button>`:''}</div></article>`}).join(''):'<div class="empty">لا توجد طلبات مطابقة.</div>'}
function renderDrivers(){let list=drivers;if(driverFilter!=='all')list=drivers.filter(d=>d.approval_status===driverFilter);$('driversCount').textContent=list.length+' سائق';$('driversCards').innerHTML=list.length?list.map(d=>{const v=vehicleFor(d.id);return `<article class="entity-card"><div class="entity-top"><div><strong class="entity-title">${esc(d.name)}</strong><span class="entity-sub" dir="ltr">${esc(d.phone)}</span></div>${badgeStatus(d.approval_status)}</div><div class="facts"><div><small>المركبة</small><b>${v?esc((v.make||'')+' '+(v.model||'')):esc(d.car_type||'—')}</b></div><div><small>اللوحة</small><b>${v?esc(v.plate_number):esc(d.car_number||'—')}</b></div><div><small>اعتماد المركبة</small><b>${v?badgeStatus(v.approval_status):'—'}</b></div><div><small>الحالة الآن</small><b>${d.is_busy?'🔴 مشغول برحلة':d.is_available?'🟢 متاح':'⚫ غير متاح'}</b></div><div><small>المنطقة</small><b>${esc(d.current_zone||'—')}</b></div><div><small>الاشتراك</small><b>${badgeStatus(d.subscription_status)}</b></div></div><div class="card-actions">${d.approval_status==='pending'?`<button class="btn btn-green" onclick="approveDriver('${d.id}','${v?.id||''}')">اعتماد السائق والمركبة</button><button class="btn btn-outline-danger" onclick="rejectDriver('${d.id}','${v?.id||''}')">رفض</button>`:''}${d.approval_status==='approved'?`<button class="btn btn-outline-danger" onclick="suspendDriver('${d.id}')">إيقاف الحساب</button>`:''}${d.approval_status==='suspended'?`<button class="btn btn-green" onclick="restoreDriver('${d.id}')">إعادة التفعيل</button>`:''}</div></article>`}).join(''):'<div class="empty">لا يوجد سائقون في هذه الفئة.</div>'}
function renderSubscriptions(){$('subscriptionCards').innerHTML=drivers.length?drivers.map(d=>`<article class="entity-card compact-card"><div class="entity-top"><div><strong class="entity-title">${esc(d.name)}</strong><span class="entity-sub">${d.subscription_status==='trial'?'التجربة حتى '+new Date(d.trial_ends_at).toLocaleDateString('ar-AE'):d.subscription_ends_at?'حتى '+new Date(d.subscription_ends_at).toLocaleDateString('ar-AE'):''}</span></div>${badgeStatus(d.subscription_status)}</div><div class="card-actions"><button class="btn btn-yellow" onclick="activateMonth('${d.id}')">تفعيل 30 يومًا</button></div></article>`).join(''):'<div class="empty">لا يوجد سائقون.</div>'}
$('searchInput').oninput=renderRides;$('statusFilter').onchange=renderRides;
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>openView(b.dataset.view));window.openView=name=>{document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view-section').forEach(v=>v.classList.add('hidden'));$(name+'View').classList.remove('hidden')};
document.querySelectorAll('.subtab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.subtab').forEach(x=>x.classList.remove('active'));b.classList.add('active');driverFilter=b.dataset.driverFilter;renderDrivers()});
window.approveDriver=async(id,vehicleId)=>{if(!confirm('اعتماد هذا السائق والمركبة؟'))return;const a=await sb.from('drivers').update({approval_status:'approved'}).eq('id',id);if(a.error)return alert(a.error.message);if(vehicleId){const b=await sb.from('vehicles').update({approval_status:'approved'}).eq('id',vehicleId);if(b.error)return alert(b.error.message)}await loadAll()};
window.rejectDriver=async(id,vehicleId)=>{if(!confirm('رفض التسجيل؟'))return;await sb.from('drivers').update({approval_status:'rejected',is_available:false}).eq('id',id);if(vehicleId)await sb.from('vehicles').update({approval_status:'rejected'}).eq('id',vehicleId);await loadAll()};
window.suspendDriver=async id=>{if(!confirm('إيقاف حساب السائق؟'))return;const {error}=await sb.from('drivers').update({approval_status:'suspended',is_available:false}).eq('id',id);if(error)alert(error.message);else loadAll()};
window.restoreDriver=async id=>{const {error}=await sb.from('drivers').update({approval_status:'approved'}).eq('id',id);if(error)alert(error.message);else loadAll()};
window.activateMonth=async id=>{const end=new Date();end.setDate(end.getDate()+30);const {error}=await sb.from('drivers').update({subscription_status:'active',subscription_ends_at:end.toISOString()}).eq('id',id);if(error)alert(error.message);else loadAll()};
window.cancelRide=async id=>{if(!confirm('إلغاء هذا الطلب؟'))return;const {error}=await sb.from('ride_requests').update({status:'cancelled',dispatch_state:'cancelled'}).eq('id',id);if(error)alert(error.message);else loadAll()};
boot();
